global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "nginx-proxy"
    static_configs:
      - targets: ["nginx-proxy:8080"]
    metrics_path: "/nginx_status"
    scrape_interval: 5s

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "elasticsearch"
    static_configs:
      - targets: ["elasticsearch:9200"]
    metrics_path: "/_prometheus/metrics"
    scrape_interval: 30s

  - job_name: "logstash"
    static_configs:
      - targets: ["logstash:9600"]
    metrics_path: "/_node/stats"
    scrape_interval: 30s
